// appRow implementation moved from src/components/appRow/appRow.cpp
#include "appRow.h"
#include <QBrush>
#include <QHBoxLayout>
#include <QIcon>
#include <QPainter>
#include <QPixmap>
#include <QString>

const QString AppRow::rowStyle =
    "AppRow {\n"
    "  background-color: rgba(255, 255, 255, 10);\n"
    "  border-radius: 8px;\n"
    "}\n"
    "AppRow:hover {\n"
    "  background-color: rgba(155, 255, 255, 30);\n"
    "}\n";

const QString AppRow::iconStyle =
    "QLabel {\n"
    "  color: white;\n"
    "  font-size: 18px;\n"
    "}\n";

const QString AppRow::nameStyleTemplate =
    "QLabel {\n"
    "  color: white;\n"
    "  font-size: %1px;\n"
    "}\n";

AppRow::AppRow(QWidget *parent, const DesktopApp &app, prefs::Preferences *prefs) : QWidget(parent), app(app)
{
    // Use a stable object name so QSS can target AppRow widgets
    this->setObjectName("AppRow");
    // Store the app name for accessibility/debugging
    this->setProperty("appName", QString::fromStdString(app.name));
	this->setToolTip(QString::fromStdString(app.comment.value_or("")));
	this->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Fixed);

    // Do not set per-instance stylesheet here; prefer global QSS generated by ThemeManager
    // so styles apply consistently. Keep rowStyle as a fallback but don't apply it.

	QHBoxLayout *layout = new QHBoxLayout(this);
	layout->setSpacing(4);
	layout->setContentsMargins(8, 4, 8, 4);
	layout->setAlignment(Qt::AlignVCenter | Qt::AlignLeft);

	QLabel *iconLabel = new QLabel(this);

	bool iconSet = false;
	if (app.icon)
	{
		QString iconName = QString::fromStdString(app.icon.value());
		QIcon icon = QIcon::fromTheme(iconName);
		if (!icon.isNull())
		{
			iconLabel->setPixmap(icon.pixmap(ICON_SIZE, ICON_SIZE));
			iconSet = true;
		}
	}

	if (!iconSet)
	{
		QPixmap pixmap(ICON_SIZE, ICON_SIZE);
		pixmap.fill(Qt::transparent);
		QPainter painter(&pixmap);
		painter.setRenderHint(QPainter::Antialiasing);

		painter.setBrush(QBrush(QColor(100, 100, 100)));
		painter.setPen(Qt::NoPen);

		painter.drawRoundedRect(0, 0, ICON_SIZE, ICON_SIZE, 4, 4);

		painter.setPen(Qt::white);
		QFont font = painter.font();
		font.setBold(true);
		font.setPointSize(ICON_SIZE / 2);
		painter.setFont(font);
		painter.setRenderHint(QPainter::TextAntialiasing);
		painter.drawText(pixmap.rect(), Qt::AlignCenter,
										 QString::fromStdString(app.name.substr(0, 1)));

		painter.end();
		iconLabel->setPixmap(pixmap);
	}

	iconLabel->setAlignment(Qt::AlignVCenter | Qt::AlignLeft);
	layout->addWidget(iconLabel);

    QLabel *nameLabel = new QLabel(QString::fromStdString(app.name), this);
    // Styling for the name label is provided by global QSS; avoid per-widget
    // styles that override the stylesheet so themes can apply consistently.
    nameLabel->setAlignment(Qt::AlignVCenter | Qt::AlignLeft);
    layout->addWidget(nameLabel);

    // No pin/hide buttons — removed (they were unnecessary UX noise)
    layout->addStretch();

  this->setLayout(layout);
}

// pin/hide hooks removed
