# These are example GitHub Actions for C++/Qt/CMake. Adjust as needed for your project.
name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qtbase5-dev-tools qtchooser cmake g++ make
    - name: Configure CMake
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build
